runtime: nodejs20
instance_class: F1

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  max_instances: 5
  min_pending_latency: 3000ms
  max_pending_latency: automatic

entrypoint: node server.js

env_variables:
  NODE_ENV: 'production'
